### ISSUE TITLE
Add basic UI for multiple PluginLinkedList

### ISSUE THREAD

**Issue by med1844** [still18/6106Group4#23]
## Phase 1

- [x] Create one band for each pluginLinkedList (`BandComponent`) and horizontally stack them
- [x] Create `PluginWrapperComponent` to hold plugin editors and serve as a conceptual wrapper that can be stored in `BandComponent`
- [x] For minimal functioning test, create `PluginWrapperComponent` for each of the currently hard coded plugins and display them

## Phase 2

- [x] Add open editor button in `PluginWrapperComponent`.
  - [x] Take care of the window creation & closing, as well as VST editor instance storage (do we need this?)
- [x] Add append plugin button and corresponding callback function for selecting from scanned plugin list & create `PluginWrapperComponent` & append at corresponding `BandComponent`

**Comment by med1844** [comment]
Bands can now be normally created and horizontally stacked. See bd5c69ed9e499adb25c732454559633853132814.

**Comment by med1844** [comment]
ef2ea8d57e5153770cf113c934ae4fa4ecf65815: `PluginWrapperComponent` can be created & draw now.

**Comment by med1844** [comment]
82b66f0cb556b920c32cd8dc8bae382d29f57015: `PluginWrapperComponent` can now be created according to the given `PluginLinkedList` and correctly display their names.

![image_2022-04-27_02-01-08](https://user-images.githubusercontent.com/51191710/165455378-f4ac316d-029e-42d5-b937-8c2917ef488d.png)

**Comment by med1844** [comment]
- aebf4973fed5ee763c487de40b0ef21a7173123c: edit button added using the `PluginWindow` implementation from juce's `AudioPluginHost` project. This allows us to create separate `TopLevelWindow`s, set titles, correctly close windows, create generic editor for plugins with no editors, etc.
  ![addPluginButton](https://user-images.githubusercontent.com/51191710/165862155-74ad35ac-15d3-4834-9d39-a04440b3a7b1.png)
- 77441d01a0e6af936d69e0d33ec49210f281ff8e: `addPluginButton` properly added & tested.
  ![addPluginButton2](https://user-images.githubusercontent.com/51191710/165862180-77468b20-f4b3-43a1-a853-e44afd51291f.png)
